language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

sudo: false

php:
  - 7.1
  - 7.2

env:
  - WP_VERSION=4.9.6 WP_MULTISITE=0
  - WP_VERSION=4.9.6 WP_MULTISITE=1

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=5.7.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi

  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
